language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
node_js: 12
install:
  - npm install

script:
  - npm run lint
  - npm run build

deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: master
  script:
    - npm run semantic-release
